# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

analyzers:
  ethercat:
    type: diagnostic_aggregator/AnalyzerGroup
    path: EtherCat
    analyzers:
      EtherCAT_master:
        type: diagnostic_aggregator/GenericAnalyzer
        path: EtherCAT Master
        timeout: 5.0
        regex: ['EtherCAT Master', 'EtherCAT Port.*']
        num_items: 1
  control_loop:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Realtime Control Loop
    timeout: 5.0
    startswith: 'Realtime Control Loop'
    num_items: 1